scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']

  - job_name: 'search-cep'
    scrape_interval: 10s
    static_configs:
      - targets: ['search-cep:8080']

  - job_name: 'search-weather'
    scrape_interval: 10s
    static_configs:
      - targets: ['search-weather:8081']